# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - nodebb-f24

on:
  push:
    branches:
      - f24
  workflow_dispatch:
    
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    uses:
      ./.github/workflows/test.yaml

  build-and-deploy:
    if: github.repository == 'cmu-313/nodebb-f24-boba'
    needs: lint-and-test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      - name: Set up NodeBB
        run: |
          ./nodebb setup '{"url":"https://nodebb-boba.azurewebsites.net:443",
            "admin:username": "admin",
            "admin:password": "${{ secrets.ADMIN_PASSWORD }}",
            "admin:password:confirm": "${{ secrets.ADMIN_PASSWORD }}",
            "admin:email": "rohanpadhye@cmu.edu",
            "database": "redis",
            "redis:host": "${{ secrets.REDIS_HOST }}",
            "redis:port": "6379",
            "redis:password": "${{ secrets.REDIS_PASSWORD }}" }'

      - name: Install frontend repo
        run: |
          npm i https://github.com/CMU-313/nodebb-frontend-f24-boba.git

      - name: Install frontend repo dependencies
        run: |
          npm i ./nodebb-frontend-f24-boba

      - name: Build 
        run: |
          ./nodebb build
          
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'nodebb-boba'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_347FFC7A24C04BED919EE37343BF79F7 }}
          package: .
